# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# TODO: test stage, or step if it is worth reusing the ubuntu vm (likely)
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage:  windows-2019
    steps:
    - checkout: self

    # where are we??
    - script: |
        echo
        echo current directory is:
        cd
        echo
        echo BUILD_SOURCESDIRECTORY=%BUILD_SOURCESDIRECTORY%
        echo
        if defined SWIFT_PAT echo "SWIFT_PAT is defined"
      displayName: 'Test: where repos are checked out'
    # # Configure the VM.
    # - script: |
    #     set "CI=azure"
    #     call activate base
    #     run_conda_forge_build_setup
    #   displayName: check out sources
