# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  root_src_dir: $(Build.SourcesDirectory)/s
  local_dir: $(Build.SourcesDirectory)/usr/local
  local_dev_dir: $(Build.SourcesDirectory)/usr/localdev
  include_dir: $(Build.SourcesDirectory)/usr/local/include

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage:  windows-2019
    steps:
    - checkout: self
    # where are we??
    - script: |
        echo
        echo current directory is:
        cd
        echo
        echo BUILD_SOURCESDIRECTORY=%BUILD_SOURCESDIRECTORY%
        echo
        echo Build.SourcesDirectory=$(Build.SourcesDirectory)
        echo
        echo local_dev_dir=$(local_dev_dir)
        echo
        if defined SWIFT_PAT_ENV_VAR echo "SWIFT_PAT is defined"
        echo 
        echo Bash is located at:
        where bash
      displayName: 'Test: where repos are checked out'
      env:
        SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # echo $(Build.SourcesDirectory)/data
          # mkdir -p $(Build.SourcesDirectory)/data
          # cd $(Build.SourcesDirectory)/data
          mkdir -p $(local_dir)
          cd $(local_dir)
          curl -o libs_third_party.7z https://cloudstor.aarnet.edu.au/plus/s/GdV0QmFISDHrwPG/download
          curl -o include_third_party.7z https://cloudstor.aarnet.edu.au/plus/s/cl3QJ17UV5HJkzo/download
          # which 7z  : /c/ProgramData/Chocolatey/bin/7z
          7z x libs_third_party.7z 
          7z x include_third_party.7z 
          mkdir -p $(local_dev_dir)
          # cd $(local_dev_dir)
          mkdir -p $(include_dir)
          exit 0
      displayName: 'Install third party libraries and headers'
    #- script: |
    #    call checkout.bat
    #  env:
    #    SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
    #  displayName: check out sources
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Build.SourcesDirectory)\pwsh-setup.ps1
        #arguments: > # Use this to avoid newline characters in multiline string
        #  -input1 "Hello"
        #  -input2 "World"
      displayName: 'Setup Powershell with Invoke-MsBuild'
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Build.SourcesDirectory)\make-props.ps1
      displayName: 'Create user vcpp_config.props'
    # - script: |
    #     call third-party-lib.bat
    #   env:
    #     SWIFT_PAT_ENV_VAR: $(SWIFT_PAT) # the recommended way to map to an env variable
    #   displayName: Install third party precompiled libraries boost and netcdf
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: $(Build.SourcesDirectory)\build-stack.ps1
        arguments: > # Use this to avoid newline characters in multiline string
          -rootSrcDir $(rootSrcDir) 
          -localDir $(local_dir) 
          -localDevDir $(local_dev_dir) 
          -includeDir $(include_dir) 

      displayName: 'Compile with Invoke-MsBuild'
