# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# TODO: test stage, or step if it is worth reusing the ubuntu vm (likely)
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage:  windows-2019
    steps:
    - checkout: self
    - task: Bash@3
      displayName: 'Test: where repos are checked out'
      inputs:
        targetType: 'inline'
        script: |
          echo Build.SourcesDirectory=$(Build.SourcesDirectory)
          ls /
          ls /d
